name: models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dart_mappable: ^2.0.2
  freezed_annotation: ^2.1.0

dev_dependencies:
  build_verify: ^3.0.0
  build_runner: ^2.3.3
  dart_mappable_builder: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0
  freezed: ^2.2.1
