name: models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: ^2.0.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_verify: ^3.1.0
  build_runner: ^2.3.3
  dart_mappable_builder: ^2.0.2
  lints: ^2.0.1
  test: ^1.23.1
  freezed: ^2.3.2
