targets:
  freezed:
    builders:
      freezed:freezed:
        enabled: true
  $default:
    dependencies:
      # TODO: Change this value when changing the package name
      - flutter_boolean_template:freezed
    builders:
      freezed:freezed:
        enabled: false
      dart_mappable_builder:
        # Generates for any imported files in the following locations (including nested imports)
        generate_for:
          - lib/main.dart # modify this if you have a different entry point
          - lib/src/models.dart # multiple independent entry files
