name: flutter_boolean_template

packages:
  - packages/*

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

# See https://github.com/firebase/flutterfire/blob/master/melos.yaml for more examples
scripts:
  analyze:
    run: flutter analyze && melos exec -- flutter analyze .
    description: Run `flutter analyze` in all packages.

  format:
    run: dart format . && melos exec -- dart format .
    description: Run `dart format` in all packages.

  generate:
    run: melos run build:pkg --no-select
    description: Run `build_runner build` in all packages.

  generate:pkg:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner build` in the selected packages.
    packageFilters:
      failFast: true
      dependsOn: build_runner
      ignore: localization

  test:pkg:
    exec: flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test
      failFast: true

  test:
    run: flutter test --no-pub --coverage && melos run test:pkg --no-select
    description: Run all Flutter tests in this project.

  loc:
    run: melos exec --scope="localization" --dir-exists="lib/src/translations" --fail-fast -- flutter gen-l10n
    description: Run `flutter gen-l10n` in the localization package.
