name: app_workspace

packages:
  - packages/*

scripts:
  analyze:
    exec: dart analyze .
  build:
    exec: dart run build_runner build --delete-conflicting-outputs
  watch:
    exec: dart run build_runner watch --delete-conflicting-outputs