name: flutter_boolean_template

packages:
  - packages/*

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    usePubspecOverrides: true

# See https://github.com/firebase/flutterfire/blob/master/melos.yaml for more examples
scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `flutter analyze` in all packages.

  format:
    run: melos exec -- dart format .
    description: Run `dart format` in all packages.

  build:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner build` in all packages.

  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  test:
    run: flutter test --no-pub --coverage && melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.

  loc:
    run: melos exec --scope="localization" --dir-exists="lib/src/translations" --fail-fast -- flutter gen-l10n
    description: Run `flutter gen-l10n` in the localization package.
