name: app_workspace

packages:
  - packages/*

scripts:
  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.
  build:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner build` in all packages.