name: auth_example
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^1.0.6
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  models:
    path: ../../models

dev_dependencies:
  build_verify: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^1.0.6
  build_runner: ^2.3.3
  custom_lint: ^0.2.5
  riverpod_lint: ^1.0.0

flutter:
