name: auth_example
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.1.1
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  domain:
    path: ../../layers/domain
  fpdart: ^0.6.0

dev_dependencies:
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.2.3
  build_runner: any
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2

flutter:
