// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 1.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'assets';

  static const String packagesAssetsImagesFlutterLogoPng =
      'packages/assets/images/flutter_logo.png';
}
