name: sidebarx
description: flutter multiplatform navigation sidebar / side navigationbar / drawer widget
version: 0.17.0
homepage: https://github.com/Frezyx/sidebarx
repository: https://github.com/Frezyx/sidebarx

topics:
  - widget
  - ui
  - drawer
  - navigation
  - sidebar

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
