name: localization
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  hooks_riverpod: ^2.3.6
  intl: any

dev_dependencies:
  app_lints:
    path: ../app_lints
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
