name: env
description: A new Flutter package which provides environment variables for the app. These variables can also be obfuscated.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  envied:
    git:
      url: https://github.com/getBoolean/envied.git
      ref: null_value_support_testing
      path: packages/envied
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  fpdart: ^1.1.0
  constants:
    path: ../constants

dev_dependencies:
  build_runner: ^2.4.5
  envied_generator:
    git:
      url: https://github.com/getBoolean/envied.git
      ref: null_value_support_testing
      path: packages/envied_generator
  flutter_test:
    sdk: flutter

flutter:
