name: app
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^7.1.2
  localization:
    path: ../localization
  feature_first:
    path: ../features/feature_first
  routing:
    path: ../routing
  constants:
    path: ../constants
  leak_tracker: ^4.0.0
  env:
    path: ../utils/env
  hooks_riverpod: ^2.3.6
  fpdart: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.0.1
