name: app
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.2.0
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^6.1.2
  localization:
    path: ../localization
  models:
    path: ../models
  auth_example:
    path: ../features/auth_example
  routing:
    path: ../features/routing
  leak_tracker: ^2.0.1
  env:
    path: ../utils/env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  custom_lint: ^0.2.5
  riverpod_lint: ^1.0.1
