name: app
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  convenient_test: ^1.2.1
  hive: ^2.2.3
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  mason: ^0.1.0-dev.38
  mocktail: ^0.3.0
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^6.0.1
  localization:
    git:
      url: https://github.com/getBoolean/flutter_boolean_template
      path: packages/localization
  models:
    git:
      url: https://github.com/getBoolean/flutter_boolean_template
      path: packages/models
  features:
    git:
      url: https://github.com/getBoolean/flutter_boolean_template
      path: packages/features

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
