name: features
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^1.0.6
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1
  models:
    path: ../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^1.0.6
  build_runner: ^2.3.3

flutter:
