name: env
description: A new Flutter package which provides environment variables for the app. These variables can also be obfuscated.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6

dev_dependencies:
  build_runner: any
  envied_generator: ^0.3.0
  lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
