name: env
description: A new Flutter package which provides environment variables for the app. These variables can also be obfuscated.
version: 0.0.1

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  envied: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
