name: assets
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  assets_gen: ^1.5.0

flutter:
  # Must specify full path to each asset, directories will not work
  # since this is in a package. All assets must also be in the lib directory.
  #
  # Run the generator with `melos run assets`
  assets:
    - packages/assets/images/flutter_logo.png

assets_gen:
  code_style: lowerCamelCase
  format_dart_code: true
  gen_package_path: false
  output: src/assets.dart
