name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: ^3.0.1
  fpdart: ^0.6.0
  http: ^1.0.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  modddels_annotation_fpdart: ^0.1.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_verify: ^3.1.0
  build_runner: any
  dart_mappable_builder: ^3.0.2
  lints: ^2.0.1
  test: ^1.23.1
  riverpod_generator: ^2.2.3
  modddels: ^0.1.3
  freezed: ^2.3.5
